name: WakaTime ReadMe Updater

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          
          CODE_LANG: rust
          BLOCKS: "▱▰"

          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          
          COMMIT_MESSAGE: "📈 Updated Dev Metrics"
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
